### PR TITLE
Add Matthew's photo

### PR DESCRIPTION
**Pull request by matthewyip1511**
Thanks for reviewing 🙂

### CODE REVIEW

**Comment by RezwanAhmed123** [comment]
LGTM

**Comment by yanqiyqh** [comment]
LGTM :)

**Comment by zi-yii** [comment]
LGTM

**Comment by RezwanAhmed123** [comment]
OK done

**Comment by RezwanAhmed123** [comment]
LGTM

**Review by RezwanAhmed123 — COMMENTED** [review]
LGTM

**Review by zi-yii — COMMENTED** [review]
LGTM

**Review by yanqiyqh — APPROVED** [review]
lgtm!

**Pull request merged**
